name: AI Pull Request Review

on:
  pull_request:
    types: [ready_for_review]

jobs:
  review:
    # Skip if PR is labeled as trivial
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'trivial') }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run AI PR Review
        uses: timcharper/ai-pull-review@v3.0.0-rc2
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
